name: Exploration GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Execution tests
    runs-on: ubuntu-latest
    steps:
      - name: Recuperation de code
        run: echo "Recuperation de code"
      - name: Installation Node.js
        run: echo "Installation Node.js"
      - name: Installation dependences
        run: echo "Installation dependences"
      - name: Execution tests
        run: echo "Execution tests"
  build:
    name: Build
    runs-on: ubuntu-latest
    # avec needs, on indique que ce job doit attendre la fin du job test pour se lancer
    needs: test
    steps:
      - name: Recuperation de code
        run: echo "Recuperation de code"
      - name: Installation Node.js
        run: echo "Installation Node.js"
      - name: Installation dependences
        run: echo "Installation dependences"
      - name: Build
        run: echo "Build"
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # avec needs, on indique que ce job doit attendre la fin du job build pour se lancer
    needs: build 
    steps:
      - name: Connexion au serveur        
        run: echo "Connexion au serveur"
      - name: Mise en route du serveur        
        run: echo "Mise en route du serveur"
      - name: Deploy
        run: echo "Deploy"